Display appropriate message in all invoice action
kushal-dreamspring/parking_lot_rb pull request #11
Opened 2023-06-15 08:28 UTC by kushal-dreamspring

- Display 'No Invoice Found' if invoice not present
- Display correct invoice number and exit time if invoice is present

2023-06-26 06:08 UTC, jinifrancis requested changes
Here also I am not able to see related specs for the code updates made here. Can you add the necessary specs for these actions?

2023-06-26 06:08 UTC, jinifrancis commented on app.rb
>    end
You can move the `print_invoice` method to the invoice controller instead of keeping it in `app.rb`. It is an action related to invoice. Or if it is a common method to be used by multiple controllers, create a helper module that can be included in both the controllers, so that the same method can be used by both the controllers.

2023-06-26 06:08 UTC, jinifrancis commented on app.rb
>  Duration: #{invoice[:duration]}
These 4 attributes are part of car - `invoice[registration_number]` looks incorrect. You can get the car from invoice and then use the car object to print these here.

2023-06-26 06:08 UTC, jinifrancis commented on controller/invoice.rb
> +    Car.join(:invoices, car_id: :id).all
Fetch the invoice and not the car from Invoice controller.

2023-06-26 06:08 UTC, jinifrancis commented on controller/invoice.rb
> +    Car.join(Invoice.where(id: invoice_id), car_id: :id).first
Fetch and return the invoice and not the car in the Invoice controller

2023-06-26 08:17 UTC, kushal-dreamspring commented on app.rb
>  Duration: #{invoice[:duration]}
In my models, apart from the registration number, all the other fields are part of the invoice model. The reasoning being a car may enter the parking more than once.That is why I have done it this way

2023-06-26 10:05 UTC, kushal-dreamspring commented on app.rb
>    end
Should I also move print_all_invoices to invoice controller??

2023-06-27 10:33 UTC, jinifrancis commented on app.rb
>    end
Yes. I see that you have already moved it in your new commit. Any action specific to a model, should ideally be in the controller specific to that model. If you have an invoice controller, any action specific to that should be routed to that invoice controller.

2023-07-03 11:40 UTC, jinifrancis commented on app.rb
>  Duration: #{invoice[:duration]}
Got it. Further changes can be looked into when I do the code review. I'll check the functionality and proceed with this PR if it is working.

2023-07-03 12:06 UTC, jinifrancis requested changes
I still see that the exit time of the vehicle is incorrect when I print the invoice.
Ex:
Entry Time: 2023-06-27 16:10:20 +0530
Exit Time: 2023-06-27 10:40:29 +0530
Duration: 9

Time-wise, this looks incorrect. Please verify the logic used to save the exit time.

2023-07-03 12:11 UTC, jinifrancis commented
Also, make the entry time and exit time into a readable format when printing out details of the invoice.
Ex: July 3, 2023 17:37:38 IST instead of 2023-07-03 17:37:38 +0530

2023-07-11 10:57 UTC, jinifrancis commented
All specs are not passing in this PR. Please check and fix the issue.
<img width="797" alt="Screenshot 2023-07-11 at 4 26 54 PM" src="https://github.com/kushal-dreamspring/parking_lot_rb/assets/17831956/e6f94616-47ae-4cc7-b1dd-49239b00f222">

2023-07-14 10:39 UTC, jinifrancis approved these changes
You can merge this PR!

2023-07-17 05:10 UTC, merged